feature: new endpoints for communities
vocdoni/vote-frame pull request #59
Opened 2024-04-15 12:25 UTC by lucasmenendez

Closes #58

2024-04-17 14:20 UTC, p4u requested changes

2024-04-17 14:20 UTC, p4u commented on census.go
> +	// extract userFID from auth token
This should be done at the beginning of the method and we should check if the user calling the endpoint is actually an admin for the community.

2024-04-17 14:20 UTC, p4u commented on census.go
> +	if community.Census.Type == mongo.TypeCommunityCensusChannel {
Please move this code to a separate function and try to reuse the one already existing for creating channel censuses.

2024-04-18 14:00 UTC, p4u requested changes

2024-04-18 14:00 UTC, p4u commented on census.go
> +	censusType := ERC20type
Nit: a switch case works better here and it's more extensible to other censuses in the future

2024-04-18 14:00 UTC, p4u commented on census.go
> +	userFID, err := v.db.UserFromAuthToken(msg.AuthToken)
We should check if the userFID is allowed to create census for such community

2024-04-18 14:00 UTC, p4u commented on census.go
> +		return fmt.Errorf("cannot create erc20 census: %w", err)
error message is wrong, its not always 'erc20 census'

2024-04-18 14:00 UTC, p4u commented on communities.go
> +			if err == farcasterapi.ErrChannelNotFound {
This is weird. Why are you just wrapping the ErrChannelNotFound error (returning 404) while other error are 500? Both errors should be wrapper or none. I'd say not to wrap the error and just return whatever the v.censusChannelOrAddresses() method returns with a 404.

2024-04-18 14:00 UTC, p4u commented on communities.go
> +				continue
Do not silent the errors please, it's ok to keep going but print it at least as a Warning on the logs.

2024-04-18 15:10 UTC, lucasmenendez commented on farcasterapi/neynar/neynar.go
> +func (n *NeynarAPI) FindChannel(ctx context.Context, query string) ([]*farcasterapi.Channel, error) {
There is no alternative to neynar to get information about channels. They are not in the farcaster protocol, internally they are like a thread of a parent cast (the channel itself), and their properties are not registered in the hubs (such as followers count or followers list).

2024-04-18 15:11 UTC, lucasmenendez commented on farcasterapi/neynar/neynar.go
> +func (n *NeynarAPI) FindChannel(ctx context.Context, query string) ([]*farcasterapi.Channel, error) {
Discover and track channels requires to create a service to scan internally using the Neynar API.

2024-04-18 15:36 UTC, p4u commented on farcasterapi/neynar/neynar.go
> +func (n *NeynarAPI) FindChannel(ctx context.Context, query string) ([]*farcasterapi.Channel, error) {
Still wondering what happens if the query is empty. And wondering also if we should handle this situation.

2024-04-18 15:46 UTC, p4u approved these changes

2024-04-18 15:47 UTC, merged